// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Card: typeof import('./../components/Card/index.vue')['default']
    DialogForm: typeof import('./../components/DialogForm/index.vue')['default']
    Draggable: typeof import('./../components/Draggable/index.vue')['default']
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    PageContainer: typeof import('./../components/PageContainer/index.vue')['default']
    Pagination: typeof import('./../components/Pagination/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../components/SvgIcon/index.vue')['default']
    TestJsx: typeof import('./../components/TestJsx.vue')['default']
    TextEditor: typeof import('./../components/TextEditor/index.vue')['default']
  }
}

export {}
